In [1]:
import numpy as np

## numpy Array

In [2]:
benimListem = [20,30,40]

In [3]:
np.array(benimListem)

array([20, 30, 40])

In [4]:
matrixList = [[10,20,30],[40,50,60],[70,80,90]]

In [5]:
matrixList[1][2]

60

In [6]:
np.array(matrixList)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## arange

In [7]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## zeros


In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

## linspace


In [11]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

## eye


In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random


In [13]:
np.random.randn(3,3)

array([[ 0.61502917, -0.13297268, -1.19727163],
       [ 1.49306203,  0.76240976, -0.95266181],
       [-1.0010558 ,  0.62619574,  0.79166278]])

In [14]:
np.random.randint(2,10)

4

In [15]:
np.random.randint(2,10,6)

array([2, 2, 2, 9, 7, 7])

In [16]:
benimNumpyDizi = np.arange(30)

In [17]:
benimNumpyDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
benimRandomDizi = np.random.randint(0,100,20)

In [19]:
benimRandomDizi

array([10, 30, 14, 25, 25, 85, 45, 83, 70, 53, 75, 42, 11, 15, 91,  5, 76,
       32, 88, 81])

## Numpy Dizi Methodları


In [20]:
benimNumpyDizi.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [21]:
benimNumpyDizi.max()

29

In [22]:
benimRandomDizi.argmax()

14

In [23]:
benimNumpyDizi.shape

(30,)

In [24]:
yeniDizi = benimNumpyDizi.reshape(5,6)

In [25]:
yeniDizi.shape

(5, 6)

In [26]:
yeniDizi

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## Numpy Operasyonlar(Indexler)


In [27]:
myDizi = np.arange(0,15)

In [28]:
myDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
myDizi[5]

5

In [30]:
myDizi[2:6]

array([2, 3, 4, 5])

In [31]:
myDizi[2:6] = -5

In [32]:
myDizi

array([ 0,  1, -5, -5, -5, -5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
slicingDizi = myDizi[2:6]

In [34]:
slicingDizi

array([-5, -5, -5, -5])

In [35]:
slicingDizi[:] = 50

In [36]:
slicingDizi

array([50, 50, 50, 50])

In [37]:
myDizi #slicing degisince asıl dizi de degisti

array([ 0,  1, 50, 50, 50, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Matrix


In [38]:
matrixListe = np.arange(1,10)

In [39]:
matrixListe

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
matrixListe[:] = matrixListe[:]*10

In [41]:
matrixListe

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
matrixListe = matrixListe.reshape(3,3)

In [43]:
matrixListe

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [44]:
matrixListe[0]

array([10, 20, 30])

In [45]:
matrixListe[1:,2]

array([60, 90])

In [46]:
matrixListe[0:,2]

array([30, 60, 90])

## Matrix Indexler


In [47]:
ornekMatrixDizisi = np.arange(1,9)

In [48]:
ornekMatrixDizisi

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
ornekMatrixDizisi = np.append(ornekMatrixDizisi,9)

In [50]:
ornekMatrixDizisi

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Operasyonlar


In [52]:
yeniBirD = np.random.randint(1,100,20)
yeniBirD

array([60, 58, 63, 66, 17, 76, 21, 54, 63, 69, 41, 36, 71, 40, 65, 81, 93,
       38, 68, 10])

In [53]:
yeniBirD > 24

array([ True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [54]:
sonDizi = np.arange(0,24)

In [56]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [58]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])